/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.exercise;

/**
 * Classe principal.
 */
public class App {

  /**
   * Método inicial.
   */
  public static void main(String[] args) {

    PasswordManager passwordManager = new PasswordManager();
    
    passwordManager.manager();
  }
}
