/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.exercise;

public class App {

  public static void main(String[] args) {

    FuncionarioPessoaFisica pessoaFisica = new FuncionarioPessoaFisica();
    pessoaFisica.setSalarioBruto(5000);

    System.out.println("O salário líquido pessoa física: "
        + pessoaFisica.calcularSalarioLiquido());
    
    
    FuncionarioPessoaJuridica pessoaJuridica = new FuncionarioPessoaJuridica();
    pessoaJuridica.setSalarioBruto(5000);    

    System.out.println("O salário líquido pessoa jurídica: "
        + pessoaJuridica.calcularSalarioLiquido());
  }
}
