/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.exercise;

import java.util.Scanner;

/**
 * marcusWittho.
 */
public class App {

  public static void menu(String title) {
    System.out.println("Cadastrar pessoa " + title + "?");
    System.out.println("1 - Sim\n2 - Não\nEntre com o número correspondente à opção desejada:");
  }

  /**
   * Método inicial.
   */
  public static void main(String[] args) {

    GerenciamentoVotacao gerenciamentoVotacao = new GerenciamentoVotacao();

    try (Scanner scan = new Scanner(System.in)) {
      short opcaoMenu;
      String nome;
      String cpf;
      int numero;

      do {
        menu("candidata");

        opcaoMenu = scan.nextShort();

        if (opcaoMenu != 1 && opcaoMenu != 2) {
          System.out.println("Digite um número válido.");
          continue;
        }

        if (opcaoMenu == 2) {
          break;
        }

        if (opcaoMenu == 1) {
          System.out.println("Entre com o nome da pessoa candidata:");
          nome = scan.next();

          System.out.println("Entre com o número da pessoa candidata:");
          numero = scan.nextInt();

          gerenciamentoVotacao.cadastrarPessoaCandidata(nome, numero);
        }
      } while (opcaoMenu != 2);

      do {
        menu("eleitora");

        opcaoMenu = scan.nextShort();

        if (opcaoMenu != 1 && opcaoMenu != 2) {
          System.out.println("Digite um número válido.");
          continue;
        }

        if (opcaoMenu == 2) {
          break;
        }

        if (opcaoMenu == 1) {
          System.out.println("Entre com o nome da pessoa eleitora:");
          nome = scan.next();

          System.out.println("Entre com o cpf da pessoa eleitora:");
          cpf = scan.next();

          gerenciamentoVotacao.cadastrarPessoaEleitora(nome, cpf);
        }
      } while (opcaoMenu != 2);

      do {
        System.out.println("Entre com o número correspondente à opção desejada:");
        System.out.println("1 - Votar\n2 - Resultado parcial\n3 - Finalizar votação");

        opcaoMenu = scan.nextShort();

        if (opcaoMenu != 1 && opcaoMenu != 2 && opcaoMenu != 3) {
          System.out.println("Digite um número válido.");
          continue;
        }

        if (opcaoMenu == 3) {
          gerenciamentoVotacao.mostrarResultado();
          scan.close();
          break;
        }

        if (opcaoMenu == 2) {
          gerenciamentoVotacao.mostrarResultado();
          continue;
        }

        if (opcaoMenu == 1) {
          System.out.println("Entre com o cpf da pessoa eleitora:");
          cpf = scan.next();

          System.out.println("Entre com o número da pessoa candidata:");
          numero = scan.nextInt();

          gerenciamentoVotacao.votar(cpf, numero);
        }
      } while (opcaoMenu != 2);
    }
  }
}
