/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.exercise;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  @DisplayName("1 - Verificando o cálculo do funcionário pessoa física.")
  void calculoPessoaFisica() {
    FuncionarioPessoaFisica pessoaFisica = new FuncionarioPessoaFisica();
    pessoaFisica.setSalarioBruto(5000);
    assertEquals(4000, pessoaFisica.calcularSalarioLiquido());
  }
  
  @Test
  @DisplayName("2 - Verificando o cálculo do funcionário pessoa jurídica.")
  void calculoPessoaJuridica() {
    FuncionarioPessoaJuridica pessoaJuridica = new FuncionarioPessoaJuridica();
    pessoaJuridica.setSalarioBruto(5000);
    assertEquals(4500, pessoaJuridica.calcularSalarioLiquido());
  }
}
