/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.exercise;

/**
 * Classe principal.
 */
public class App {

  /**
   * Método inicial.
   */
  public static void main(String[] args) {
    
    Square sq1 = new Square(8);
    Triangle tr1 = new Triangle(4, 27);
    Rectangle rc1 = new Rectangle(5.5, 9);
    Circle c1 = new Circle(13);
    
    Square sq2 = new Square(12);
    Triangle tr2 = new Triangle(6, 32);
    Rectangle rc2 = new Rectangle(3.5, 20);
    Circle c2 = new Circle(8);
    
    Farm[] farmsP1 = {sq1, tr1, rc1, c1};
    Farm[] farmsP2 = {sq2, tr2, rc2, c2};

    PlayerResult player1 = new PlayerResult("Jogador 1", farmsP1);  
    PlayerResult player2 = new PlayerResult("Jogador 2", farmsP2);  
    
    System.out.println("Nome: " + player1.getPlayerName() + "\nPontos: " + player1.score());
    System.out.println("\nNome: " + player2.getPlayerName() + "\nPontos: " + player2.score());
  }
}
